# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d928a73e2a17c4b8715a52d30dd1631d903fc91dd7ab33be91f5de18779b98cd2ea638b23534d87b488d6e74c47b8136266fa2ebfc404d419b88358ae6167c

test:
  secret_key_base: fd8b40756b926e7e0afb245d3ae268d8b1ed93c1885d4301a1560ec2e7ad8c305e74e7b6263145b454d01ea5deaf20ee12d33d80044fb3c119053100faee211a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
